# LIST vs. NUMPY

In [27]:
height = [1.60, 1.70, 1.80, 1.90]
weight = [50, 60, 70, 80]

In [40]:
weight / height

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [41]:
import numpy as np
np_height = np.array(height)
np_height

array([1.6, 1.7, 1.8, 1.9])

In [29]:
np_weight = np.array(weight)
np_weight

array([50, 60, 70, 80])

In [30]:
bmi = np_weight / (np_height ** 2)
bmi

array([19.53125   , 20.76124567, 21.60493827, 22.16066482])

In [31]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [32]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [33]:
numpy_array + numpy_array

array([2, 4, 6])

Numpy Subsetting
 - if you want to get all BMI values in the 'bmi' array that are over 20.

In [36]:
bmi

array([19.53125   , 20.76124567, 21.60493827, 22.16066482])

In [37]:
bmi[1]

20.761245674740486

In [38]:
bmi > 20

array([False,  True,  True,  True])

In [42]:
bmi[bmi > 20]

array([20.76124567, 21.60493827, 22.16066482])

In [43]:
x = [4 , 9 , 6, 3, 1]
x[1]

9

In [44]:
import numpy as np
y = np.array(x)
y[1]

9

In [46]:
high = y > 5
y[high]

array([9, 6])

NUMPY FEATURES
- 1. numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

- 2. Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

In [48]:
np.array([True, 1, 2]) + np.array([3, 4, False])
# True is converted to 1, False is converted to 0.

array([4, 5, 2])

Subsetting NumPy Arrays
- : works exactly the same like LIST

In [50]:
x = ["a", "b", "c"]
x[1]

'b'

In [51]:
np_x = np.array(x)
np_x[1]

'b'

2d Numpy Array : Subsetting

In [55]:
np_2d = np.array([[1,2,3],[4,5,6]])
np_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np_2d[0]

array([1, 2, 3])

In [57]:
np_2d[0][2]

3

In [59]:
np_2d[0,2] # same

3

In [60]:
 np_2d[:,1:3] # [ (전체)열, 행 ]

array([[2, 3],
       [5, 6]])

In [61]:
np_2d[1, :] # 1열 전체 행

array([4, 5, 6])

In [62]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

['a', 'c']

In [63]:
# numpy
import numpy as np
np_x = np.array(x)
np_x[:,0]

array(['a', 'c'], dtype='<U1')

In [65]:
np_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
np_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np_3d[2,:]

array([7, 8, 9])

In [90]:
np.mean(np_3d[2,:])

8.0

In [95]:
np.median(np_3d[2,:])

8.0

In [96]:
np.corrcoef(np_3d[:,0], np_3d[:,1])

array([[1., 1.],
       [1., 1.]])

In [97]:
np.std(np_3d[2,:])

0.816496580927726

In [98]:
np.sum(np_3d)

45

In [100]:
np.sort(np_3d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
# np.random.normal()
# (distribution mean, distribution standard deviation, number of samples)
height = np.round(np.random.normal(1.75, 0.20, 5000),2)
weight = np.round(np.random.normal(60.32, 15, 5000),2)

In [121]:
np_city = np.column_stack((height,weight))

In [122]:
np_city

array([[ 1.74, 77.91],
       [ 1.51, 56.83],
       [ 1.7 , 56.55],
       ...,
       [ 2.07, 60.79],
       [ 1.63, 61.37],
       [ 1.62, 70.69]])

In [111]:
?np.random.normal

In [107]:
?round